os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH="$PATH":"$HOME/.pub-cache/bin"
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter precache
  - flutter doctor -v
script:
  - cd app
  - flutter packages get
  - flutter packages pub run build_runner build --delete-conflicting-outputs
  - flutter test --coverage
cache:
  directories:
    - $HOME/.pub-cache
after_success: bash <(curl -s https://codecov.io/bash)
